---

version: "3"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: assembly
    ports:
      - "5432:5432"

  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_USER: system76
      MYSQL_PASSWORD: system76
      MYSQL_ROOT_PASSWORD: system76
      MYSQL_DATABASE: inventory
    ports:
      - "3306:3306"
